GET /posts にlimit とoffsetをつける
givery-bootcamp/dena-2024-team3 pull request #27
Opened 2024-05-28 05:37 UTC by daiki0381

# issue
#16

2024-05-28 05:39 UTC, shake551 requested changes
ちょっとコメントしたー

2024-05-28 05:39 UTC, shake551 commented on backend/internal/interface/api/handler/post_handler.go
> +	}
ここデフォルトとかは入れたほうがいいかも

2024-05-28 05:39 UTC, shake551 commented on backend/internal/domain/repository/post_repository.go
> +	GetAll(ctx context.Context, limit int, offset int) ([]*model.Post, error)
IMO
```suggestion
	GetAll(ctx context.Context, limit, offset int) ([]*model.Post, error)
```

2024-05-28 05:39 UTC, shake551 commented on backend/internal/infrastructure/persistence/datastore/post_repository.go
> +func (r *PostRepository) GetAll(ctx context.Context, limit int, offset int) ([]*model.Post, error) {
IMO
```suggestion
func (r *PostRepository) GetAll(ctx context.Context, limit, offset int) ([]*model.Post, error) {
```

2024-05-28 05:39 UTC, shake551 commented on backend/internal/interface/api/handler/post_handler.go
> +	}
背景として昔書いた記事
https://zenn.dev/shake_sanma/articles/64f36c49cc3441

2024-05-28 05:43 UTC, yamoyamoto approved these changes
自分的にはLGTM

2024-05-28 08:02 UTC, daiki0381 commented on backend/internal/infrastructure/persistence/datastore/post_repository.go
> +func (r *PostRepository) GetAll(ctx context.Context, limit int, offset int) ([]*model.Post, error) {
[7632067](https://github.com/givery-bootcamp/dena-2024-team3/pull/27/commits/7632067fbcbf96a9675fb45a05c8abbbe293b0bf)で修正した！

2024-05-28 08:02 UTC, daiki0381 commented on backend/internal/domain/repository/post_repository.go
> +	GetAll(ctx context.Context, limit int, offset int) ([]*model.Post, error)
[7632067](https://github.com/givery-bootcamp/dena-2024-team3/pull/27/commits/7632067fbcbf96a9675fb45a05c8abbbe293b0bf)で修正した！

2024-05-28 08:03 UTC, daiki0381 commented on backend/internal/interface/api/handler/post_handler.go
> +	}
[947703c](https://github.com/givery-bootcamp/dena-2024-team3/pull/27/commits/947703c2c7a6a978d6601bd0e0c498140108e030)で修正した！

2024-05-28 09:09 UTC, daiki0381 commented
@shake551 指摘された場所修正したから再レビューお願い！

2024-06-11 03:03 UTC, shake551 approved these changes
LGTM!

2024-06-11 04:31 UTC, merged