feat: 記事投稿API
givery-bootcamp/dena-2024-team3 pull request #29
Opened 2024-05-28 07:43 UTC by yamoyamoto

2024-05-28 07:53 UTC, shake551 reviewed
まだ途中だと思うけど、一個だけ気になったのでコメントしとく

2024-05-28 07:53 UTC, shake551 commented on backend/internal/infrastructure/persistence/datastore/entity/post.go
> +func NewFromModel(p *model.Post) *Post {
ここentity psckage内で衝突するから、NewPostFromModelとかの名前の方がいいかも

2024-05-28 08:58 UTC, yamoyamoto commented on backend/internal/infrastructure/persistence/datastore/entity/post.go
> +func NewFromModel(p *model.Post) *Post {
ありがとうたしかに！なおした！

- https://github.com/givery-bootcamp/dena-2024-team3/commit/a1309955fe656cf930c00bc975b76cca39808a5c

2024-06-11 03:10 UTC, shake551 requested changes
何個かコメントしたー

2024-06-11 03:10 UTC, shake551 commented on backend/internal/infrastructure/persistence/datastore/post_repository.go
> +	}
これってselectせずid取れないんだっけ？
https://gorm.io/docs/create.html#Create-Record

2024-06-11 03:10 UTC, shake551 commented on backend/internal/interface/api/router/router.go
> +			postRoute.Use(middleware.CheckToken()).POST("/", ph.Create)
今後も認証いるrouteはあると思う（更新、削除とか）から、ちゃんとroute作ってあげたほうがいいかな

2024-06-11 03:10 UTC, shake551 commented on backend/internal/application/usecase/post_usecase.go
> +func (u *PostUsecase) Create(ctx context.Context, title string, body string, userId int) (*model.Post, error) {
ここってなんで全部そのまま受け取ってるんだっけ？

2024-06-11 03:59 UTC, yamoyamoto commented on backend/internal/infrastructure/persistence/datastore/post_repository.go
> +	}
うおこれで取れるのか！知らなかったありがとう！！なおします！

2024-06-11 04:00 UTC, yamoyamoto commented on backend/internal/interface/api/router/router.go
> +			postRoute.Use(middleware.CheckToken()).POST("/", ph.Create)
@shake551 
確かにそうだよなぁ

でも同じRoute(`apiRoute.Group`)でも認証が必要なものと必要ないものがあるから、どうグルーピングしたらいいかちょっと自分では悩ましくて、、アイデアあったら教えて欲しいです！

2024-06-11 04:01 UTC, yamoyamoto commented on backend/internal/application/usecase/post_usecase.go
> +func (u *PostUsecase) Create(ctx context.Context, title string, body string, userId int) (*model.Post, error) {
@shake551
 
すまぬ、「全部そのまま」ってどういう意味かな？？

2024-06-11 04:18 UTC, shake551 commented on backend/internal/application/usecase/post_usecase.go
> +func (u *PostUsecase) Create(ctx context.Context, title string, body string, userId int) (*model.Post, error) {
titleとか、bodyとかを展開して渡してるのなんでだろと思って、、
モデルを渡すようにする方が自然な感じしたから意図を聞きたかったって感じ

2024-06-11 04:26 UTC, shake551 commented on backend/internal/interface/api/router/router.go
> +			postRoute.Use(middleware.CheckToken()).POST("/", ph.Create)
あーその中でグループ切る感じかな、、

```go
		postRoute := apiRoute.Group("/posts")
		{
			postRoute.GET("/", ph.GetAll)
                         authPostRoute := apiRoute.Group("/")
                         authPostRoute.Use(middleware.HogeFuga())
                         {
                                 authPostRoute.POST("/", ph.Create)
                          }
                 }
```

```go
                apiRoute := apiRoute.Group("/api")

		postRoute := apiRoute.Group("/posts")
		{
			postRoute.GET("/", ph.GetAll)
                 }

                 authRoute := apiRoute.Group("/")
                 authRoute.Use(middleware.HogeFuga())
                 {
                         authPostRoute := postRoute.Group("/")
                         {
                                 authPostRoute.POST("/", ph.Create)
                         }
                 }
```

この2パターンあるかなと思うけど、若干煩雑になるのは、仕方ない感はあるし、どっちがいいかは好みだと思う

2024-06-11 06:55 UTC, yamoyamoto commented on backend/internal/interface/api/router/router.go
> +			postRoute.Use(middleware.CheckToken()).POST("/", ph.Create)
なるほど〜ありがとう！

二択でいうと、リソースごとにまとまって方が可読性よさそうだから、前者でやってみる！

2024-06-11 07:01 UTC, yamoyamoto commented on backend/internal/application/usecase/post_usecase.go
> +func (u *PostUsecase) Create(ctx context.Context, title string, body string, userId int) (*model.Post, error) {
なるほど！

自分的にはモデル（構造体）を渡すようにすると、構造体内のフィールドがないときにコンパイルエラーにならないから引数として必要なものを明示的に渡してあげると安全かな！と思った！（引数自体もそんなに多くないし、複雑になっていないのと、モデルを渡すとUseCaseが必要としていないフィールドもスコープに入ってしまうのがちょっと気持ち悪いかな？と思った）

2024-06-11 07:02 UTC, yamoyamoto commented on backend/internal/application/usecase/post_usecase.go
> +func (u *PostUsecase) Create(ctx context.Context, title string, body string, userId int) (*model.Post, error) {
構造体にするなら、`type CreatePostUseCaseInput`的な構造体を宣言するのがいいかな？と思うけどそこまでパラメータ多くないし引数でいいかな、と思った！

2024-06-11 07:03 UTC, yamoyamoto commented on backend/internal/interface/api/router/router.go
> +			postRoute.Use(middleware.CheckToken()).POST("/", ph.Create)
修正してみた！

https://github.com/givery-bootcamp/dena-2024-team3/pull/29/commits/9726f361ad3a1c58159014183304bba8e08e84e2

2024-06-11 07:05 UTC, yamoyamoto commented
再度動作確認済み

<img width="1295" alt="image" src="https://github.com/givery-bootcamp/dena-2024-team3/assets/68677002/20545862-88b6-4bbe-b2c8-cbe58b77ff41">

2024-06-11 07:05 UTC, yamoyamoto commented on backend/internal/infrastructure/persistence/datastore/post_repository.go
> +	}
Userデータを

2024-06-11 07:12 UTC, shake551 commented on backend/internal/application/usecase/post_usecase.go
> +func (u *PostUsecase) Create(ctx context.Context, title string, body string, userId int) (*model.Post, error) {
なるほど、
それでいうと、パラメータを展開して受け取るのはあんまり良くないかも
structのフィールドがないかをチェックするのはusecaseの責務ではないかな
usecaseのモデルを作ってもいいけど、そこまでする必要はないから、ドメインモデルとかでいいんじゃないかと思うって感じかな

2024-06-11 07:17 UTC, yamoyamoto commented on backend/internal/application/usecase/post_usecase.go
> +func (u *PostUsecase) Create(ctx context.Context, title string, body string, userId int) (*model.Post, error) {
> それでいうと、パラメータを展開して受け取るのはあんまり良くないかも

ごめん、なんで展開して受け取るのがよくないのかがよくわかっていないから教えてもらえると嬉しいかも、、！

2024-06-11 07:36 UTC, shake551 approved these changes
直接話して解決

2024-06-11 07:36 UTC, shake551 commented on backend/internal/application/usecase/post_usecase.go
> +func (u *PostUsecase) Create(ctx context.Context, title string, body string, userId int) (*model.Post, error) {
IMO
```suggestion
func (u *PostUsecase) Create(ctx context.Context, title, body string, userId int) (*model.Post, error) {
```

2024-06-11 07:39 UTC, merged

2024-06-11 09:02 UTC, yamoyamoto commented on backend/internal/interface/api/router/router.go
> +			}
ありがとう！！
でもそれだと、`api/posts`配下に対して認証必要なRouteが追加される時に毎回第三引数に`,middleware.ChcekToken()`を入れないといけなくなるから、もしかしたら45行目でまとめて`authPostRoute.Use(middleware.CheckToken())`した方が見通し良さそうだと思った！