feat: 記事更新API
givery-bootcamp/dena-2024-team3 pull request #41
Opened 2024-06-11 08:42 UTC by daiki0381

#23

2024-06-17 04:54 UTC, yamoyamoto requested changes
ソースコードまだみてないけど、Descriptionみてコメントさせてもらいます！

> userIdが一致しない場合

これは [親のIssue](https://github.com/givery-bootcamp/training-app-2024/issues/13)的には400かもしれない！

401はそもそもユーザのトークンが正しくない（=認証されていない）ときに使うもので、今回はトークンは正しいけど認可が通っていないパターンだから400という意図なのだろうと思っている！

> postがない場合

これはクライアントエラーだから4xx(「userIdが一致しない場合」とまとめて400でもいいかな？)の方が良さそうかも、？

2024-06-17 05:09 UTC, yamoyamoto commented on backend/internal/infrastructure/persistence/datastore/post_repository.go
> +		})
こっちの方が型安全かも！

```suggestion
		Updates(entity.Post{
			Title: p.Title,
			Body:  p.Body,
		})
```

2024-06-17 05:14 UTC, yamoyamoto commented on backend/internal/infrastructure/persistence/datastore/post_repository.go
> +	}
この処理、本質的にはバリデーションの意図だと思うから、以下の方針はどうかな？

- UseCaseで以下の処理をする
  - `postRepository.GetById()`を呼ぶ
  - 返り値がないor返り値の`post.User.Id`が当該ユーザーのものではないときは400にする

2024-06-17 05:32 UTC, shake551 requested changes

2024-06-17 05:32 UTC, shake551 commented on backend/internal/domain/model/post.go
> +}
IMO
```suggestion
func (p *Post) UpdatePost(title, body string) {
    p.Title = title
    p.Body = body
    p.UpdatedAt = time.Now()
}
```

2024-06-17 05:32 UTC, shake551 commented on backend/internal/infrastructure/persistence/datastore/entity/post.go
> +func UpdatePostFromModel(p *model.Post) *Post {
これupdateに絞らなくても、modelからentityへのマッピングのメソッドがあれば良さそう

2024-06-17 05:32 UTC, shake551 commented on backend/internal/infrastructure/persistence/datastore/post_repository.go
> +		})
この書き方だとどのパラメータを変更するかを知ってる設計になっていて、俗にいう賢いrepositoryになってる
ここはそのままモデル渡すだけで良さそう

2024-06-17 05:32 UTC, shake551 commented on backend/internal/infrastructure/persistence/datastore/post_repository.go
> +		return nil, exception.AuthError
ここってなんでauthErrorなんだっけ？

2024-06-17 05:32 UTC, shake551 commented on backend/internal/infrastructure/persistence/datastore/post_repository.go
> +	}
ここってselectしたい意図ってなんだろう？

2024-06-17 05:32 UTC, shake551 commented on backend/internal/interface/api/router/router.go
> +        authPostRoute.PUT("/:id", ph.Update)
全体的にフォーマットできてないとこあるかも

2024-06-17 08:52 UTC, daiki0381 commented on backend/internal/infrastructure/persistence/datastore/post_repository.go
> +		})
[1c9a1a8](https://github.com/givery-bootcamp/dena-2024-team3/pull/41/commits/1c9a1a881aec02f01e492bc1aa2cc843b915ed5b)で修正した！

2024-06-17 08:53 UTC, daiki0381 commented on backend/internal/infrastructure/persistence/datastore/post_repository.go
> +	}
[ef4d23c](https://github.com/givery-bootcamp/dena-2024-team3/pull/41/commits/ef4d23c8c73246df70ae34823e2a1909d22d1039)で修正した！

2024-06-17 08:58 UTC, daiki0381 commented on backend/internal/domain/model/post.go
> +}
backend/internal/application/usecase/post_usecase.goの`updatedPost := model.UpdatePost(post, title, body)`で戻り値を受け取って、リポジトリ層に渡してるからここは今のままで良さそう？

2024-06-17 08:58 UTC, daiki0381 commented on backend/internal/infrastructure/persistence/datastore/entity/post.go
> +func UpdatePostFromModel(p *model.Post) *Post {
[ef4d23c](https://github.com/givery-bootcamp/dena-2024-team3/pull/41/commits/ef4d23c8c73246df70ae34823e2a1909d22d1039)で修正した！

2024-06-17 08:58 UTC, daiki0381 commented on backend/internal/infrastructure/persistence/datastore/post_repository.go
> +		})
[ef4d23c](https://github.com/givery-bootcamp/dena-2024-team3/pull/41/commits/ef4d23c8c73246df70ae34823e2a1909d22d1039)で修正した！

2024-06-17 08:59 UTC, daiki0381 commented on backend/internal/infrastructure/persistence/datastore/post_repository.go
> +		return nil, exception.AuthError
ここは400で良さそうだったから[ef4d23c](https://github.com/givery-bootcamp/dena-2024-team3/pull/41/commits/ef4d23c8c73246df70ae34823e2a1909d22d1039)で修正した！

2024-06-17 08:59 UTC, daiki0381 commented on backend/internal/infrastructure/persistence/datastore/post_repository.go
> +	}
ここは特に意図がないので[ef4d23c](https://github.com/givery-bootcamp/dena-2024-team3/pull/41/commits/ef4d23c8c73246df70ae34823e2a1909d22d1039)で削除しました。

2024-06-17 08:59 UTC, daiki0381 commented on backend/internal/interface/api/router/router.go
> +        authPostRoute.PUT("/:id", ph.Update)
[ef4d23c](https://github.com/givery-bootcamp/dena-2024-team3/pull/41/commits/ef4d23c8c73246df70ae34823e2a1909d22d1039)でフォーマットしました！

2024-06-17 09:03 UTC, daiki0381 commented
@yamoyamoto @shake551 修正したので再度レビューお願いします！

2024-06-18 02:13 UTC, shake551 commented on backend/internal/domain/model/post.go
> +}
あーそういうことか、これアップデートしてるんじゃなくてファクトリなのか、
だとすると、 `NewUpdatePost` とかが良いかも

2024-06-18 02:18 UTC, shake551 requested changes
何個かコメントしたー
前回見れてなかったとこもあるかも、ごめん

2024-06-18 02:18 UTC, shake551 commented on backend/internal/infrastructure/persistence/datastore/entity/post.go
> +func PostFromModel(p *model.Post) *Post {
ここファクトリだから、Newあったほうが良いかも

2024-06-18 02:18 UTC, shake551 commented on backend/internal/infrastructure/persistence/datastore/post_repository.go
> +		return nil, exception.InvalidRequestError
若干repositoryでリクエストのエラー返すの気持ち悪い気がする
not foundみたいなエラー用意して、ステータスコードは同じの返すとかかな？

あと、この書き方だとレコードがない場合以外のエラーも全部リクエストエラーになってるから、gorm.RecordNotFoundかどうかみたいなので分けた方がいいかも

2024-06-18 02:18 UTC, shake551 commented on backend/internal/application/usecase/post_usecase.go
> +) (*model.Post, error) {
NITS
Goだとあんま引数改行して書かないことが多いかも

2024-06-24 01:04 UTC, yamoyamoto commented on backend/internal/infrastructure/persistence/datastore/post_repository.go
> +	}
ごめん、意図をちゃんと伝えられていなかった🙇‍♂️

記事の「取得」は他人のものもできるから、PostRepositoryにuserIdを渡してSQLクエリしてしまうと自分のものしか見れなくなってしまう！

イメージとしてはこんな感じだった！良さそうであればこのブランチにマージしてしまってほしい！

https://github.com/givery-bootcamp/dena-2024-team3/pull/65

2024-06-24 02:55 UTC, daiki0381 commented on backend/internal/application/usecase/post_usecase.go
> +) (*model.Post, error) {
[8ea3b15](https://github.com/givery-bootcamp/dena-2024-team3/pull/41/commits/8ea3b155b2cfcb4338d6bb3a8e6b59fab7a2656e)で修正した！

2024-06-24 02:55 UTC, daiki0381 commented on backend/internal/infrastructure/persistence/datastore/entity/post.go
> +func PostFromModel(p *model.Post) *Post {
[21c307b](https://github.com/givery-bootcamp/dena-2024-team3/pull/41/commits/21c307b180b83e261ea4485f76e2262f246b5c77)で修正した！

2024-06-24 03:24 UTC, daiki0381 commented on backend/internal/domain/model/post.go
> +}
[21c307b](https://github.com/givery-bootcamp/dena-2024-team3/pull/41/commits/21c307b180b83e261ea4485f76e2262f246b5c77)で修正しました！

2024-06-24 03:52 UTC, daiki0381 commented on backend/internal/infrastructure/persistence/datastore/post_repository.go
> +		return nil, exception.InvalidRequestError
[2cbb41e](https://github.com/givery-bootcamp/dena-2024-team3/pull/41/commits/2cbb41efac001c795b45c8b889ad8c57c8736507)で修正した！

2024-06-24 04:01 UTC, daiki0381 commented on backend/internal/domain/model/post.go
> +}
[cc1bfbb](https://github.com/givery-bootcamp/dena-2024-team3/pull/41/commits/cc1bfbbceb7dd6e4cc5fe583c45349aa623d2beb)で修正しました！

2024-06-24 04:02 UTC, daiki0381 commented
@yamoyamoto @shake551 修正したので再度レビューお願いします！

2024-06-24 05:10 UTC, shake551 requested changes
コメントしたー

2024-06-24 05:10 UTC, shake551 commented on backend/internal/application/usecase/post_usecase.go
> +		}
usecaseがgormのエラーハンドリングしてるの違和感あるかも

2024-06-24 05:10 UTC, shake551 commented on backend/internal/application/usecase/post_usecase.go
> +	}
投稿だとそんな問題ないかもだけど、アクセス権がない場合と、レコードがない場合でエラーレスポンスを変えると、レコードの存在確認ができて脆弱性になることがある

2024-06-24 05:10 UTC, shake551 commented on backend/internal/domain/model/post.go
> +func NewUpdatePost(post *Post,title string, body string) *Post {
IMO
```suggestion
func (post *Post) NewUpdatePost(title, body string) *Post {
```

がいいかな？

2024-06-24 05:34 UTC, daiki0381 commented on backend/internal/domain/model/post.go
> +func NewUpdatePost(post *Post,title string, body string) *Post {
[e54425a](https://github.com/givery-bootcamp/dena-2024-team3/pull/41/commits/e54425ad80fe21174fc681638485eba3236409e7)で修正しました。

2024-06-24 05:35 UTC, daiki0381 commented on backend/internal/application/usecase/post_usecase.go
> +		}
[6f737ee](https://github.com/givery-bootcamp/dena-2024-team3/pull/41/commits/6f737ee04cbe37746bdb2fbcc16ca44b349cd7c4)で修正しました。

2024-06-24 05:35 UTC, daiki0381 commented on backend/internal/application/usecase/post_usecase.go
> +	}
確かに、、、[52c95be](https://github.com/givery-bootcamp/dena-2024-team3/pull/41/commits/52c95bea826e3fe6eb28ee499a733680a6e45f79)で修正した！

2024-06-24 05:46 UTC, yamoyamoto approved these changes
LGTM!!!!!!!!!!!!!!!!!!!

2024-06-24 05:48 UTC, yamoyamoto commented
@daiki0381 
あっ、CI落ちてる、、すまん俺がmainにモック入れたからだ

```
$ go install go.uber.org/mock/mockgen@latest
$ cd backend
$ go generate ./...
```

でモックの更新をコミットすれば通ると思う！

2024-06-24 05:56 UTC, daiki0381 commented
@shake551 レビューありがとう！指摘もらったやつ修正した！

2024-06-24 06:50 UTC, shake551 commented on backend/internal/application/usecase/post_usecase.go
> +	}
フォーマット崩れてるかも

2024-06-24 06:52 UTC, shake551 commented on backend/internal/domain/model/post.go
> +func (post *Post) NewUpdatePost(title, body string) *Post {
IMO
```suggestion
func (post *Post) UpdatePost(title, body string) *Post {
```
ごめん、さっきコメントしたら良かったけど、これはファクトリじゃないと思うからこっちの方が良いかも？

2024-06-24 06:54 UTC, shake551 commented on backend/internal/domain/model/post.go
> +func (post *Post) NewUpdatePost(title, body string) *Post {
あれ、これ前話してたのか、
じゃあこのままでも良いのかな？
直しても直さなくてもどっちでも良いかも？

2024-06-24 07:01 UTC, daiki0381 commented on backend/internal/application/usecase/post_usecase.go
> +	}
[b4f745a](https://github.com/givery-bootcamp/dena-2024-team3/pull/41/commits/b4f745a02908fecf2d35470c7cda212e58a2f087)で修正した！

2024-06-24 07:02 UTC, daiki0381 commented on backend/internal/domain/model/post.go
> +func (post *Post) NewUpdatePost(title, body string) *Post {
ファクトリではないから[b4f745a](https://github.com/givery-bootcamp/dena-2024-team3/pull/41/commits/b4f745a02908fecf2d35470c7cda212e58a2f087)で修正しました。

2024-06-24 07:03 UTC, daiki0381 commented
指摘もらった場所直したのでマージします！

2024-06-24 07:03 UTC, merged