[WIP] add: PostUsecaseのユニットテスト
givery-bootcamp/dena-2024-team3 pull request #62
Opened 2024-06-18 08:10 UTC by yamoyamoto

- #61 

# 変更内容

WIP

2024-06-18 08:29 UTC, yamoyamoto commented on backend/internal/application/usecase/post_usecase_test.go
> +					Create(tt.ctx, test.DiffEq(tt.inputtedPost, postIgnoreFieldsOpt)).
これで特定の構造体のフィールド除いて比較できる

比較失敗したらこんな感じでわかりやすく差分出る（デフォルトのgomockの構造体比較の差分はとても見づらい、、、）

```
        --- FAIL: TestPostUsecaseTest/Create/fail (0.00s)
            post_usecase.go:33: Unexpected call to *mock_repository.MockPostRepository.Create([context.Background 0x140001b0600]) at /Users/tomoya.kawaguchi/kensyu/training-app-2024/backend/internal/application/usecase/post_usecase.go:33 because: 
                expected call at /Users/tomoya.kawaguchi/kensyu/training-app-2024/backend/internal/application/usecase/post_usecase_test.go:157 doesn't match the argument at index 1.
                Got: &{0 title1 body1 {1   0001-01-01 00:00:00 +0000 UTC 0001-01-01 00:00:00 +0000 UTC <nil>} 2024-06-18 17:26:29.11268 +0900 JST m=+0.004668043 2024-06-18 17:26:29.11268 +0900 JST m=+0.004668126 <nil>} (*model.Post)
                Want: diff(-got +want) is   &model.Post{
                        ... // 2 identical fields
                        Body:      "body1",
                        User:      {ID: 1},
                -       CreatedAt: s"2024-06-18 17:26:29.11268 +0900 JST m=+0.004668043",
                +       CreatedAt: s"2024-06-18 17:26:29.111676 +0900 JST m=+0.003664126",
                -       UpdatedAt: s"2024-06-18 17:26:29.11268 +0900 JST m=+0.004668126",
                +       UpdatedAt: s"2024-06-18 17:26:29.111676 +0900 JST m=+0.003664168",
                        DeletedAt: nil,
                  }
            controller.go:98: missing call(s) to *mock_repository.MockPostRepository.Create(is equal to context.Background (context.backgroundCtx), diff(-got +want) is   &model.Post{
                        ... // 2 identical fields
                        Body:      "body1",
                        User:      {ID: 1},
                -       CreatedAt: s"2024-06-18 17:26:29.11268 +0900 JST m=+0.004668043",
                +       CreatedAt: s"2024-06-18 17:26:29.111676 +0900 JST m=+0.003664126",
                -       UpdatedAt: s"2024-06-18 17:26:29.11268 +0900 JST m=+0.004668126",
                +       UpdatedAt: s"2024-06-18 17:26:29.111676 +0900 JST m=+0.003664168",
                        DeletedAt: nil,
                  }
                ) /Users/tomoya.kawaguchi/kensyu/training-app-2024/backend/internal/application/usecase/post_usecase_test.go:157
            controller.go:98: aborting test due to missing call(s)
```

2024-06-18 08:29 UTC, yamoyamoto commented on backend/internal/pkg/test/test.go
モックのEXPECTに渡す引数のMatcherを独自に実装

optsにOption渡すことでgo-cmpで行える比較ロジックを注入できる

2024-06-18 08:46 UTC, xxarupakaxx requested changes
テスト項目が少ないって感じたぐらい！

2024-06-18 08:46 UTC, xxarupakaxx commented on .github/workflows/ci.yml
> +      uses: actions/checkout@v2
checkout@4とかでいいと思う

2024-06-18 08:46 UTC, xxarupakaxx commented on .github/workflows/ci.yml
> +      uses: actions/setup-go@v3
これも`@4`で

2024-06-18 08:46 UTC, xxarupakaxx commented on .github/workflows/ci.yml
> +      run: go test ./... --cover
最後改行足りてないｗ
それと -v で詳細にだしていいかも
-coverprofile=coverage.txtでconverageをprofileしてもいい

2024-06-18 08:46 UTC, xxarupakaxx commented on backend/internal/domain/model/user.go
> +		UpdatedAt: time.Now(),
ちょっと誤差が出る可能性があるから、t := time.NOW()したものを入れたほうが良いかも

2024-06-18 08:46 UTC, xxarupakaxx commented on backend/internal/domain/repository/hello_world_repository.go
> +//go:generate mockgen -source=hello_world_repository.go -destination=mock/hello_world_repository_mock.go
こういうのはファイルの1行目に書くかも

2024-06-18 08:46 UTC, xxarupakaxx commented on backend/internal/domain/repository/post_repository.go
> +//go:generate mockgen -source=post_repository.go -destination=mock/post_repository_mock.go
ここも

2024-06-18 08:46 UTC, xxarupakaxx commented on backend/internal/domain/repository/user_repository.go
> +//go:generate mockgen -source=user_repository.go -destination=mock/user_repository_mock.go
ここも

2024-06-18 08:46 UTC, xxarupakaxx commented on backend/internal/application/usecase/post_usecase_test.go
> +				name:          "fail",
なぜfailするのかの説明を書いてほしい
それかname以外のdescriptionフィールドをつけて説明とか(nameを変えても良い）

2024-06-18 08:46 UTC, xxarupakaxx commented on backend/internal/application/usecase/post_usecase_test.go
> +				name:          "fail",
ここも

2024-06-18 08:46 UTC, xxarupakaxx commented on backend/internal/application/usecase/post_usecase_test.go
> +				repositoryErr: nil,
逆にbodyがなかったらエラーを吐くのか

2024-06-18 08:46 UTC, xxarupakaxx commented on backend/internal/application/usecase/post_usecase_test.go
> +				repositoryErr: nil,
titleとかも

2024-06-18 08:46 UTC, xxarupakaxx commented on backend/internal/application/usecase/post_usecase_test.go
> +					Create(tt.ctx, test.DiffEq(tt.inputtedPost, postIgnoreFieldsOpt)).
これすげーーーー便利

2024-06-18 08:50 UTC, yamoyamoto commented on backend/internal/application/usecase/post_usecase_test.go
> +				repositoryErr: nil,
今の所はUsecaseに空のtitle, body渡してもエラーは吐かないようになってる！

2024-06-18 08:51 UTC, xxarupakaxx commented on backend/internal/application/usecase/post_usecase_test.go
> +				repositoryErr: nil,
それをテストケースに書いてほしい！

2024-06-18 08:57 UTC, yamoyamoto commented on backend/internal/domain/repository/hello_world_repository.go
> +//go:generate mockgen -source=hello_world_repository.go -destination=mock/hello_world_repository_mock.go
なおした！

[refactor: go generateコメントはファイルの一行目に](https://github.com/givery-bootcamp/dena-2024-team3/pull/62/commits/d37bb85216990059c02ceab8c08b266df6e03f00)

2024-06-18 08:58 UTC, yamoyamoto commented on backend/internal/domain/repository/post_repository.go
> +//go:generate mockgen -source=post_repository.go -destination=mock/post_repository_mock.go
なおした！

[refactor: go generateコメントはファイルの一行目に](https://github.com/givery-bootcamp/dena-2024-team3/pull/62/commits/d37bb85216990059c02ceab8c08b266df6e03f00)

2024-06-18 08:58 UTC, yamoyamoto commented on backend/internal/domain/repository/user_repository.go
> +//go:generate mockgen -source=user_repository.go -destination=mock/user_repository_mock.go
なおした！

[refactor: go generateコメントはファイルの一行目に](https://github.com/givery-bootcamp/dena-2024-team3/pull/62/commits/d37bb85216990059c02ceab8c08b266df6e03f00)

2024-06-18 08:58 UTC, yamoyamoto commented on backend/internal/domain/model/user.go
> +		UpdatedAt: time.Now(),
おっしゃる通りだ！なおした！

[refactor: CreatedAt, UpdatedAtは共通のtimeを使う](https://github.com/givery-bootcamp/dena-2024-team3/pull/62/commits/7b918305deab033e64adeabfa6627a7dca84f700)

2024-06-18 09:00 UTC, yamoyamoto commented on .github/workflows/ci.yml
> +      uses: actions/setup-go@v3
すまん！setup-goははv5出たみたいだからv5にしてみた！

[chore: 最新のActionを使う](https://github.com/givery-bootcamp/dena-2024-team3/pull/62/commits/695b5c10848a196d1908ffb6a06f2a1078c1c2ab)

2024-06-18 09:01 UTC, yamoyamoto commented on backend/internal/application/usecase/post_usecase_test.go
> +				name:          "fail",
おっしゃる通りだ、修正してみた！

[refactor: テスト名を詳細に](https://github.com/givery-bootcamp/dena-2024-team3/pull/62/commits/fe428b0b24d9f3e8503a96d4dda953014ad2293c)

2024-06-18 09:01 UTC, yamoyamoto commented on backend/internal/application/usecase/post_usecase_test.go
> +				name:          "fail",
おっしゃる通りだ、修正してみた！

[refactor: テスト名を詳細に](https://github.com/givery-bootcamp/dena-2024-team3/pull/62/commits/fe428b0b24d9f3e8503a96d4dda953014ad2293c)

2024-06-18 09:03 UTC, yamoyamoto commented on backend/internal/application/usecase/post_usecase_test.go
> +				repositoryErr: nil,
なるほど！でも正常系のテストケースにそういうのを書くのむずくないかな、、？
そういう仕様を全部書いてたら保守辛い気がした、、

異常系のテストケースに落ちる理由を書くのは大賛成！！！

2024-06-18 09:03 UTC, shake551 commented on .github/workflows/ci.yml
> +      run: go mod download
この辺キャッシュできるといいかも

2024-06-18 09:03 UTC, shake551 commented on backend/internal/domain/model/user.go
> +}
これってテストのためのメソッド？

2024-06-18 09:05 UTC, yamoyamoto commented on backend/internal/domain/model/user.go
> +}
いや、普通に本番コードでも使う想定！

テスト書く時にたまたま必要だったから追加した感じです！

2024-06-18 09:05 UTC, yamoyamoto commented on backend/internal/application/usecase/post_usecase_test.go
> +	mock_repository "myapp/internal/domain/repository/mock"
`mock`だけだとちょっと可読性悪いかなぁ、と思ってたけどUsecaseはRepositoryのモックしか使わないしいらないか

2024-06-18 09:08 UTC, yamoyamoto commented on backend/internal/application/usecase/post_usecase_test.go
> +	mock_repository "myapp/internal/domain/repository/mock"
なんかエイリアス消したらコンパイル通らない、、？ `mock`って特殊なpackage名だったっけ、、？

![image](https://github.com/givery-bootcamp/dena-2024-team3/assets/68677002/6c0b2bb1-4338-4d6c-b05b-3a740c0e0eab)

2024-06-18 09:11 UTC, yamoyamoto commented on .github/workflows/ci.yml
> +      run: go mod download
確かに、ちょっと調べないといけなくて時間かかりそうだから別Issueで対応でいいかな？？

https://github.com/givery-bootcamp/dena-2024-team3/issues/63

2024-06-18 09:12 UTC, yamoyamoto commented on .github/workflows/ci.yml
> +      run: go test ./... --cover
それはそうだな、、ありがとう！！

codev入れる時に対応しようと思います！

2024-06-18 09:21 UTC, xxarupakaxx commented on backend/internal/application/usecase/post_usecase_test.go
> +				repositoryErr: nil,
逆にアプリの保守性が高まると思ってるよ
ここでtitle=""でも動きましたっていう仕様だったのが、validate設定して一文字以上ないといけないとかになった場合にテストで検知でバグの検知が行えるし
> なるほど！でも正常系のテストケースにそういうのを書くのむずくないかな、、？
そういう仕様を全部書いてたら保守辛い気がした、、

2024-06-18 09:22 UTC, xxarupakaxx commented on backend/internal/application/usecase/post_usecase_test.go
> +				repositoryErr: nil,
今これで動くっていう確信を持つためにもtestケースはpassするもんとfailするものはどちらも詳しく書くべきだと思ってる

2024-06-18 09:37 UTC, yamoyamoto commented on backend/internal/application/usecase/post_usecase_test.go
> +				repositoryErr: nil,
直接話して解決

とりあえず正常系はテストケース詳細に描かなくてもいっか的な的になった

2024-06-18 09:37 UTC, xxarupakaxx approved these changes
# LGTM

![](https://cdn.discordapp.com/emojis/577150584696602644.gif?size=128)

2024-06-24 04:18 UTC, yamoyamoto commented on backend/internal/application/usecase/post_usecase_test.go
> +	mock_repository "myapp/internal/domain/repository/mock"
ごめん普通にpackage名間違えてただけだったわ、、なおした！

[refactor: package名修正](https://github.com/givery-bootcamp/dena-2024-team3/pull/62/commits/8318c5d7fcdb11896c0ca3bcacf6698118b56821)

2024-06-24 04:22 UTC, shake551 commented on .github/workflows/ci.yml
> +      run: go mod download
良さそうー

2024-06-24 04:22 UTC, shake551 commented on backend/internal/domain/model/user.go
> +}
なるほど、じゃあ良さそう

2024-06-24 04:23 UTC, shake551 commented on backend/internal/application/usecase/post_usecase_test.go
> +	mock_repository "myapp/internal/domain/repository/mock"
pakage名が読みにくいなら、生成するパッケージ名を変えればいいかなと思った。
mockだけだと分かりにくいってのは同意だから、repository_mockとかで良さそう

2024-06-24 04:31 UTC, yamoyamoto commented on backend/internal/application/usecase/post_usecase_test.go
> +	mock_repository "myapp/internal/domain/repository/mock"
なおした！

https://github.com/givery-bootcamp/dena-2024-team3/pull/62/commits/e85ba8a90fb8e71787d7d5ee3ee106183d65e286

なんか自分のVsCodeの設定で自動でエイリアスつけるみたいだった、まぁこれでいいかなとおもた！

2024-06-24 04:40 UTC, shake551 commented on backend/internal/domain/repository/post_repository.go
> +//go:generate mockgen -source=post_repository.go -destination=mock/post_repository_mock.go
```suggestion
//go:generate mockgen -source=post_repository.go -destination=repository_mock/post_repository_mock.go
```

こういうイメージ

2024-06-24 04:40 UTC, shake551 commented on backend/internal/application/usecase/post_usecase_test.go
> +	mock_repository "myapp/internal/domain/repository/mock"
ごめん、ちゃんと伝わってなかったから、suggestion出した

2024-06-24 04:48 UTC, yamoyamoto commented on backend/internal/domain/repository/post_repository.go
> +//go:generate mockgen -source=post_repository.go -destination=mock/post_repository_mock.go
なるほど！ありがとう！パスが`repository/repository_mock`ってなるけど仕方ないか！

2024-06-24 04:55 UTC, yamoyamoto commented on backend/internal/domain/repository/post_repository.go
> +//go:generate mockgen -source=post_repository.go -destination=mock/post_repository_mock.go
修正しました！` -package repository_mock`をつけないとpackageが`mock_repository`にされてしまうから追加した！

https://github.com/givery-bootcamp/dena-2024-team3/pull/62/commits/99ecefeb00e9ed94827573bff313db357b29b7c2

2024-06-24 04:57 UTC, shake551 commented on backend/internal/domain/repository/post_repository.go
> +//go:generate mockgen -source=post_repository.go -destination=mock/post_repository_mock.go
あーなるほど、そこに出してるのか、
階層もう一つ上げてもいいかも

2024-06-24 04:57 UTC, shake551 approved these changes
一点コメントしたけど、どっちでも良さそう

2024-06-24 05:00 UTC, yamoyamoto commented on backend/internal/domain/repository/post_repository.go
> +//go:generate mockgen -source=post_repository.go -destination=mock/post_repository_mock.go
ありがとう！
主役は`repository`で、脇役が`repository_mock`だから`repository/repository_mock`に入れても良さそうかなとはお思っていた、ちょい気持ち悪いけど

2024-06-24 05:00 UTC, merged