feat: 記事削除API
givery-bootcamp/dena-2024-team3 pull request #82
Opened 2024-06-24 06:47 UTC by daiki0381

close #24

## 動作確認

## 正常系（userIdがログインしているuserと一致&postがある場合）

<img width="837" alt="スクリーンショット 2024-06-24 15 41 28" src="https://github.com/givery-bootcamp/dena-2024-team3/assets/98577773/66bc52be-8b7a-4fcf-9dae-39024e6b00b9">

## 異常系（userIdが一致しない場合/postがない場合）

<img width="848" alt="スクリーンショット 2024-06-24 15 41 47" src="https://github.com/givery-bootcamp/dena-2024-team3/assets/98577773/2909f488-ec7b-497d-b072-44e7d60361fa">

<img width="840" alt="スクリーンショット 2024-06-24 15 41 38" src="https://github.com/givery-bootcamp/dena-2024-team3/assets/98577773/621b1ffc-3d72-461f-bd47-678d230bbe50">

2024-06-24 06:58 UTC, shake551 requested changes
コメントしたー

2024-06-24 06:58 UTC, shake551 commented on backend/internal/application/usecase/post_usecase.go
> +	}
ここフォーマットできてないかも

2024-06-24 06:58 UTC, shake551 commented on backend/internal/application/usecase/post_usecase.go
> +	post, err := u.GetByID(ctx, postId)
これってなんで一旦getしてるんだっけ？

2024-06-24 06:58 UTC, shake551 commented on backend/internal/exception/exception.go
> +  RecordNotFoundError = newException(http.StatusNotFound, "レコードが見つかりませんでした", 0)
ここもフォーマットできてないかも

2024-06-24 06:58 UTC, shake551 commented on backend/internal/infrastructure/persistence/datastore/post_repository.go
> +	}
分けて消すならトランザクション貼ったほうが良いかも

2024-06-24 07:21 UTC, yamoyamoto approved these changes
LGTM!!

2024-06-24 07:21 UTC, yamoyamoto commented on backend/internal/domain/repository/post_repository.go
> +	Delete(ctx context.Context, postId int) error
無茶苦茶細かいけど、`GetById`と合わせた方がいいかも！

```suggestion
	Delete(ctx context.Context, id int) error
```

2024-06-24 07:32 UTC, daiki0381 commented on backend/internal/domain/repository/post_repository.go
> +	Delete(ctx context.Context, postId int) error
[e04d642](https://github.com/givery-bootcamp/dena-2024-team3/pull/82/commits/e04d6424209616aa1b95386222c6c0faf2cb9cb0)で修正しました。

2024-06-24 07:32 UTC, daiki0381 commented on backend/internal/infrastructure/persistence/datastore/post_repository.go
> +	}
[ade246a](https://github.com/givery-bootcamp/dena-2024-team3/pull/82/commits/ade246a0d8e2c64c8f99a603c68c3a40996def12)で修正しました。

2024-06-24 07:33 UTC, daiki0381 commented on backend/internal/exception/exception.go
> +  RecordNotFoundError = newException(http.StatusNotFound, "レコードが見つかりませんでした", 0)
[f265ea0](https://github.com/givery-bootcamp/dena-2024-team3/pull/82/commits/f265ea06e228837f72cacce534fa3536335bc834)で修正した！

2024-06-24 07:33 UTC, daiki0381 commented on backend/internal/application/usecase/post_usecase.go
> +	}
[f265ea0](https://github.com/givery-bootcamp/dena-2024-team3/pull/82/commits/f265ea06e228837f72cacce534fa3536335bc834)で修正した！

2024-06-24 07:34 UTC, daiki0381 commented on backend/internal/application/usecase/post_usecase.go
> +	post, err := u.GetByID(ctx, postId)
削除対象の投稿が存在するかどうか確認して、なければエラーを返してそれ以降の削除処理を行わないようにするためかな。この処理がなくてもDeleteの部分で投稿が存在しない場合はエラーは返ってくるとは思う。

2024-06-24 07:35 UTC, daiki0381 commented
@yamoyamoto ありがと〜！
@shake551 修正したので再度レビューお願い！

2024-06-25 01:06 UTC, shake551 approved these changes
yosasou

2024-06-25 02:17 UTC, merged